# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 193980c916c88fa36b023501c01bcf4aad364f7a2cbac0cb04e946b252f4460e325e7b26c98a80ba1b182f5d1dfbb9aba7d1b9a2c3a215a239211d69c01bbb7c

test:
  secret_key_base: e432d92ed7ae9fa1bcee69f434d4a1a9bdb7e94657f6bc45bda0e74cc8761bc150b63f58b83d172dbe83082f9cd79b920ac6dd6d4c1c0788d85e8141d4a52dee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
